### ISSUE TITLE
How to decode har file?

### ISSUE THREAD

**Issue by QGB** [JustusW/harparser#1]

**Comment by JustusW** [comment]
Please consult the https://github.com/JustusW/harparser/blob/master/README since the usage section answers your question quite specifically.

**Comment by QGB** [comment]
more demo?

**Comment by JustusW** [comment]
I have no idea how to make the basic usage example any simpler than it is, take any string (in the following example from a file) and put it into the function:

```
from harparser import HAR
f = file("some.json")
my_har = HAR.log().json(f.read())
```
