### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by dufferzafar** [JustusW/harparser#3]
Apart from the standard stuff like `s/iteritems/items` we'll also need to decide what should happen when binary data is passed etc.

**Comment by JustusW** [comment]
Due to the major changes to class and instance handling I'm not even certain whether this approach would still be wise. Gotta take a look at the new Metaclasses and stuff ;)

**Comment by JustusW** [comment]
I have no time at all anymore and sadly stopped working with python altogether. So sorry, but unless someone comes along and forks this you're out of luck.

**Comment by JustusW** [comment]
Kinda reopened, with the latest commit. Feel free to test. I'll look into all requests as soon as I got the time.

**Comment by JustusW** [comment]
By the lack of replies I kinda assume that it works. Feel free to reopen.
